# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import pandas as pd
import csv


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 600, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 5, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 190, 350, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet(
            '''QPushButton{background:#F0F8FF;}QPushButton:hover{background:98FB98;}''')
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet(
            '''QPushButton{background:#F0F8FF;}QPushButton:hover{background:98FB98;}''')
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet(
            '''QPushButton{background:#F0F8FF;}QPushButton:hover{background:98FB98;}''')
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet(
            '''QPushButton{background:#F0F8FF;}QPushButton:hover{background:98FB98;}''')
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(380, 190, 250, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 3, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 15, 401, 21))
        self.label_11.setObjectName("label_11")

        # 设置字体大小
        self.lineEdit.setStyleSheet("font-size:23px")
        self.lineEdit_2.setStyleSheet("font-size:23px")
        self.lineEdit_3.setStyleSheet("font-size:23px")
        self.lineEdit_4.setStyleSheet("font-size:23px")
        self.lineEdit_5.setStyleSheet("font-size:23px")
        self.lineEdit_6.setStyleSheet("font-size:23px")
        self.lineEdit_7.setStyleSheet("font-size:23px")
        self.lineEdit_8.setStyleSheet("font-size:23px")
        self.label_11.setStyleSheet("font-size:23px")
        self.label.setStyleSheet("font-size:23px")
        self.label_2.setStyleSheet("font-size:23px")
        self.label_3.setStyleSheet("font-size:23px")
        self.label_4.setStyleSheet("font-size:23px")
        self.label_5.setStyleSheet("font-size:23px")
        self.label_7.setStyleSheet("font-size:23px")
        self.pushButton.setStyleSheet("font-size:23px")
        self.pushButton_2.setStyleSheet("font-size:23px")
        self.pushButton_3.setStyleSheet("font-size:23px")
        self.pushButton_4.setStyleSheet("font-size:23px")
        self.label_6.setStyleSheet("font-size:23px")
        self.label_8.setStyleSheet("font-size:23px")
        self.label_9.setStyleSheet("font-size:23px")
        self.label_10.setStyleSheet("font-size:23px")
        self.label_11.setStyleSheet("font-size:20px")

        # self.gridLayoutWidget.setStyleSheet("background:#E8E8E8")  设置布局颜色

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 180, 611, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        # self.line_2 = QtWidgets.QFrame(self.centralwidget)
        # self.line_2.setGeometry(QtCore.QRect(340, 190, 20, 151))
        # self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        # self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_7.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_4)
        self.label.setBuddy(self.lineEdit_3)
        self.label_4.setBuddy(self.lineEdit_2)
        self.label_3.setBuddy(self.lineEdit_5)
        self.label_5.setBuddy(self.lineEdit_6)
        self.label_9.setBuddy(self.lineEdit_8)
        self.label_6.setBuddy(self.lineEdit_7)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_3)
        MainWindow.setTabOrder(self.lineEdit_3, self.lineEdit_4)
        MainWindow.setTabOrder(self.lineEdit_4, self.lineEdit_2)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit_5)
        MainWindow.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        MainWindow.setTabOrder(self.lineEdit_6, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.lineEdit_7)
        MainWindow.setTabOrder(self.lineEdit_7, self.lineEdit_8)
        self.pushButton.clicked.connect(self.cao1)
        self.pushButton_2.clicked.connect(self.cao2)
        self.pushButton_3.clicked.connect(self.cao3)
        self.pushButton_4.clicked.connect(self.cao4)

    def cao1(self):
        print("读取待测溶液的光强，并将获取的数据送入到预测模型中")

        x1 = self.lineEdit.text()
        x2 = self.lineEdit_3.text()
        x3 = self.lineEdit_4.text()
        x4 = self.lineEdit_2.text()
        x5 = self.lineEdit_5.text()
        x6 = self.lineEdit_6.text()
        print(u'x1: %s x2: %s x3: %s x4: %s x5: %s x6: %s' % (x1, x2, x3, x4, x5, x6))
        data = np.array([x1, x2, x3, x4, x5, x6])
        # 保存为a.csv
        with open('a.csv', 'w', newline='') as file:
            a = csv.writer(file, delimiter=',')
            a.writerow(data)

        # 读取文件
        # with open('a.csv', 'r', newline='') as file:
        #     a = csv.reader(file, delimiter=',')
        #     for rows in a:
        #         print(rows)

    def cao2(self):
        import joblib
        print("将送入到预测模型的数据进行预测，显示出牛奶蛋白质和脂肪的含量")
        regr_1 = joblib.load('train_model_protein.m')  # 加载模型  蛋白质protain
        regr_2 = joblib.load('train_model_fat.m')  # 加载模型  脂肪fat

        test_data = pd.read_csv("a.csv", encoding="unicode_escape", header=None)  # 读取数据

        pred_test1 = regr_1.predict(test_data)  # 输出预测值protain
        pred_test2 = regr_2.predict(test_data)  # 输出预测值fat

        print('%.5f' % pred_test1)
        print('%.5f' % pred_test2)
        self.lineEdit_8.setText(str('%.2f' % pred_test1))
        self.lineEdit_7.setText(str('%.2f' % pred_test2))

    def cao3(self):
        print("保存预测数据")
        x1 = self.lineEdit.text()
        x2 = self.lineEdit_3.text()
        x3 = self.lineEdit_4.text()
        x4 = self.lineEdit_2.text()
        x5 = self.lineEdit_5.text()
        x6 = self.lineEdit_6.text()
        protain = self.lineEdit_8.text()
        fat = self.lineEdit_7.text()
        print(u'x1: %s x2: %s x3: %s x4: %s x5: %s x6: %s protain: %s fat: %s' % (x1, x2, x3, x4, x5, x6, protain, fat))
        data2 = np.array([x1, x2, x3, x4, x5, x6, protain, fat])
        # 保存为result.csv
        with open('result.csv', 'w', newline='') as file:
            result = csv.writer(file, delimiter=',')
            result.writerow(data2)

    def cao4(self):
        print("退出应用程序")
        app = QApplication.instance()
        app.quit()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Milk Content Analysis Software"))   # 设置窗口标题
        MainWindow.setWindowIcon(QtGui.QIcon("./raspberry.png"))  # 设置窗口图标
        self.label_7.setText(_translate("MainWindow", "610nm"))
        self.label_2.setText(_translate("MainWindow", "730nm"))
        self.label.setText(_translate("MainWindow", "680nm"))
        self.label_4.setText(_translate("MainWindow", "760nm"))
        self.label_3.setText(_translate("MainWindow", "810nm"))
        self.label_5.setText(_translate("MainWindow", "860nm"))
        self.pushButton.setText(_translate("MainWindow", "Read"))
        self.pushButton_2.setText(_translate("MainWindow", "Measure"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Close"))
        self.label_9.setText(_translate("MainWindow", "Protein"))
        self.label_6.setText(_translate("MainWindow", "Fat"))
        self.label_8.setText(_translate("MainWindow", "g/100ml"))
        self.label_10.setText(_translate("MainWindow", "g/100ml"))
        self.label_11.setText(_translate("MainWindow", "Wavelength Intensity"))
